export const commands = [

// Anime
      {"name": "angry", "desc": "Muestra que estas molesto.", "alias": ["/angry"], "category": "anime", "uso": "mention"},
    {"name": "bleh", "desc": "Sacale la lengua a alguien.", "alias": ["/bleh"], "category": "anime", "uso": "mention"},
    {"name": "aburrido", "desc": "Muestra lo aburrido que éstas.", "alias": ["/bored", "/aburrido"], "category": "anime", "uso": "mention"},
    {"name": "beso", "desc": "Dale un beso a alguien.", "alias": ["/beso", "/kiss", "/muak", "/kisscheek"], "category": "anime", "uso": "mention"},
    {"name": "aplausos", "desc": "Aplaude.", "alias": ["/clap"], "category": "anime", "uso": "mention"},
    {"name": "café", "desc": "Toma un cafe.", "alias": ["/coffee", "/cafe"], "category": "anime", "uso": "mention"},
    {"name": "drama", "desc": "Haz un drama.", "alias": ["/dramatic", "/drama"], "category": "anime", "uso": "mention"},
    {"name": "emborracharse", "desc": "Emborrachate.", "alias": ["/drunk"], "category": "anime", "uso": "mention"},
    {"name": "embaraza", "desc": "Preña a alguien.", "alias": ["/impregnate", "/preg"], "category": "anime", "uso": "mention"},
    {"name": "reírse", "desc": "Burlate de alguien.", "alias": ["/laugh"], "category": "anime", "uso": "mention"},
    {"name": "amor", "desc": "Menciona al amor de tu vida.", "alias": ["/love", "/amor"], "category": "anime", "uso": "mention"},
    {"name": "pucheros", "desc": "Hasle pucheros a alguien.", "alias": ["/pout"], "category": "anime", "uso": "mention"},
    {"name": "puñetazo", "desc": "Dale un puñetazo a alguien.", "alias": ["/punch"], "category": "anime", "uso": "mention"},
    {"name": "correr", "desc": "¡Corre!", "alias": ["/run", "/correr"], "category": "anime", "uso": "mention"},
    {"name": "tristeza", "desc": "Menciona por quien estas triste.", "alias": ["/sad", "/triste"], "category": "anime", "uso": "mention"},
    {"name": "asustado", "desc": "Menciona a ese que te asusta.", "alias": ["/scared"], "category": "anime", "uso": "mention"},
    {"name": "seducir", "desc": "Seduce a alguien.", "alias": ["/seduce"], "category": "anime", "uso": "mention"},
    {"name": "timidez", "desc": "Menciona por quien sientes timidez", "alias": ["/shy", "/timido"], "category": "anime", "uso": "mention"},
    {"name": "dormir", "desc": "Duerme con alguien.", "alias": ["/sleep"], "category": "anime", "uso": "mention"},
    {"name": "fumar", "desc": "Fuma con alguien.", "alias": ["/smoke", "/fumar"], "category": "anime", "uso": "mention"},
    {"name": "escupe", "desc": "Escupe a alguien.", "alias": ["/spit", "/escupir"], "category": "anime", "uso": "mention"},
    {"name": "pisar", "desc": "Pisa a alguien.", "alias": ["/step", "/pisar"], "category": "anime", "uso": "mention"},
    {"name": "pensar", "desc": "Piensa profundamente...", "alias": ["/think", "/thinkhard"], "category": "anime", "uso": "mention"},
    {"name": "caminar", "desc": "Sal a caminar.", "alias": ["/walk"], "category": "anime", "uso": "mention"},
    {"name": "abrazar", "desc": "Abraza a alguien.", "alias": ["/hug"], "category": "anime", "uso": "mention"},
    {"name": "matar", "desc": "Mata a alguien.", "alias": ["/kill"], "category": "anime", "uso": "mention"},
    {"name": "comer", "desc": "Come con alguien.", "alias": ["/eat", "/nom", "/comer"], "category": "anime", "uso": "mention"},
    {"name": "guiñar", "desc": "Giñale un ojo a alguien.", "alias": ["/wink"], "category": "anime", "uso": "mention"},
    {"name": "acariciar", "desc": "Acaricia la cabeza a alguien.", "alias": ["/pat"], "category": "anime", "uso": "mention"},
    {"name": "feliz", "desc": "Sientete feliz por alguien.", "alias": ["/happy", "/feliz"], "category": "anime", "uso": "mention"},
    {"name": "bullying", "desc": "Hasle bullying a ese puto.", "alias": ["/bully"], "category": "anime", "uso": "mention"},
    {"name": "morder", "desc": "Muerde a alguien.", "alias": ["/bite"], "category": "anime", "uso": "mention"},
    {"name": "sonrojarse", "desc": "Sonrrojate por alguien.", "alias": ["/blush"], "category": "anime", "uso": "mention"},
    {"name": "saludos", "desc": "Saluda a alguien.", "alias": ["/wave"], "category": "anime", "uso": "mention"},
    {"name": "bañarse", "desc": "Bañate con alguien.", "alias": ["/bath"], "category": "anime", "uso": "mention"},
    {"name": "presumir", "desc": "Presume a alguien.", "alias": ["/smug"], "category": "anime", "uso": "mention"},
    {"name": "sonreir", "desc": "Sonrrie por alguien.", "alias": ["/smile"], "category": "anime", "uso": "mention"},
    {"name": "highfive", "desc": "Choca 5 con tu amigo.", "alias": ["/highfive"], "category": "anime", "uso": "mention"},
    {"name": "handhold", "desc": "Dale la mano a tu amigo.", "alias": ["/handhold"], "category": "anime", "uso": "mention"},
    {"name": "cringe", "desc": "Sientre cringe por alguien.", "alias": ["/cringe"], "category": "anime", "uso": "mention"},
    {"name": "golpe", "desc": "Dale un golpe a alguien.", "alias": ["/bonk"], "category": "anime", "uso": "mention"},
    {"name": "llorar", "desc": "Llora por alguien.", "alias": ["/cry"], "category": "anime", "uso": "mention"},
    {"name": "lamer", "desc": "Lame a alguien.", "alias": ["/lick"], "category": "anime", "uso": "mention"},
    {"name": "bofetada", "desc": "Dale una bofetada a alguien.", "alias": ["/slap"], "category": "anime", "uso": "mention"},
    {"name": "bailar", "desc": "Baila con alguien.", "alias": ["/dance"], "category": "anime", "uso": "mention"},
    {"name": "acorrucarse", "desc": "Acorrucate con alguien.", "alias": ["/cuddle"], "category": "anime", "uso": "mention"},
    {"name": "frio", "desc": "Siente frio por alguien.", "alias": ["/cold"], "category": "anime", "uso": "mention"},
    {"name": "cantar", "desc": "Cantale a alguien.", "alias": ["/sing"], "category": "anime", "uso": "mention"},
    {"name": "cosquillas", "desc": "Hasle cosquillas a alguien.", "alias": ["/tickle"], "category": "anime", "uso": "mention"},
    {"name": "gritar", "desc": "Gritale a alguien.", "alias": ["/scream"], "category": "anime", "uso": "mention"},
    {"name": "empujar", "desc": "Empuja a alguien.", "alias": ["/push"], "category": "anime", "uso": "mention"},
    {"name": "desacuerdo", "desc": "Exclama tu desacuerdo.", "alias": ["/nope"], "category": "anime", "uso": "mention"},
    {"name": "saltar", "desc": "Salta de la felicidad.", "alias": ["/jump"], "category": "anime", "uso": "mention"},
    {"name": "calor", "desc": "Siente calor por alguien.", "alias": ["/heat"], "category": "anime", "uso": "mention"},
    {"name": "jugar", "desc": "Juega con alguien.", "alias": ["/gaming"], "category": "anime", "uso": "mention"},
    {"name": "dibujar", "desc": "Dibuja a alguien.", "alias": ["/draw"], "category": "anime", "uso": "mention"},
    {"name": "llamar", "desc": "Marcale a alguien.", "alias": ["/call"], "category": "anime", "uso": "mention"},
    {"name": "acurrucate", "desc": "Acurrucate con una almohada.", "alias": ["/snuggle"], "category": "anime", "uso": "mention"},
    {"name": "besos", "desc": "Lanza un beso a alguien.", "alias": ["/blowkiss"], "category": "anime", "uso": "mention"},
    {"name": "tropezar", "desc": "Tropieza con alguien.", "alias": ["/trip"], "category": "anime", "uso": "mention"},
    {"name": "mirar", "desc": "Quédate mirando a alguien.", "alias": ["/stare"], "category": "anime", "uso": "mention"},
    {"name": "olfatear", "desc": "Olfatea a alguien.", "alias": ["/sniff"], "category": "anime", "uso": "mention"},
    {"name": "curiosidad", "desc": "Siente curiosidad por alguien.", "alias": ["/curious"], "category": "anime", "uso": "mention"},
    {"name": "consolar", "desc": "Consola a alguien.", "alias": ["/comfort"], "category": "anime", "uso": "mention"},
    {"name": "espiar", "desc": "Espía a alguien.", "alias": ["/peek"], "category": "anime", "uso": "mention"},

// Búsqueda
    {"name": "pinterest", "desc": "Busca imágenes en pinterest.", "alias": ["/pinterest", "/pin"], "category": "search", "uso": "query"},
    {"name": "imagen", "desc": "Busca imágenes en Google.", "alias": ["/imagen", "/img"], "category": "search", "uso": "query"},
    {"name": "aptoide", "desc": "Descarga aplicaciones de aptoide.", "alias": ["/aptoide", "/apk", "/apkdl"], "category": "search", "uso": "query"},
    {"name": "ytsearch", "desc": "Busca videos de youtube.", "alias": ["/ytsearch", "/search"], "category": "search", "uso": "query"},
    {"name": "tiktoksearch", "desc": "Busca videos de tiktok.", "alias": ["/tiktoksearch"], "category": "search", "uso": "query"},


    // Download
    {"name": "facebook", "desc": "Descarga videos de facebook.", "alias": ["/facebook", "(directo)"], "category": "download", "uso": "url"},
    {"name": "instagram", "desc": "Descarga videos de instagram.", "alias": ["/instagram", "(directo)"], "category": "download", "uso": "url"},
    {"name": "tiktok", "desc": "Descarga videos de tiktok.", "alias": ["/tiktok", "(directo)"], "category": "download", "uso": "url|query"},
    {"name": "play", "desc": "Descarga videos de youtube.", "alias": ["/play", "(url directo)"], "category": "download", "uso": "audio|mp3|video|mp4 url|query"},
    {"name": "spotify", "desc": "Descarga audios de spotify.", "alias": ["/spotify"], "category": "download", "uso": "url|query"},
    {"name": "mediafire", "desc": "Descarga archivos de mediafire.", "alias": ["/mediafire", "(directo)"], "category": "download", "uso": "url|query"},
    {"name": "modapk", "desc": "Descarga apk modificadas.", "alias": ["/modapk", "apkmod"], "category": "download", "uso": "text"},

    // ECONOMÍA
    {"name": "balance", "desc": "Muestra tu balance o la de un usuario.", "alias": ["/balance", "/bal"], "category": "economia", "uso": "mention"},
    {"name": "steal", "desc": "Intenta robar coins a un usuario.", "alias": ["/steal", "/rob", "/robar"], "category": "economia", "uso": "mention"},
    {"name": "crime", "desc": "Intenta cometer un crimen.", "alias": ["/crime"], "category": "economia"},
    {"name": "givecoins", "desc": "Regala coins a un usuario.", "alias": ["/givecoins", "/pay", "/coinsgive"], "category": "economia", "uso": "cantidad|all + mention"},
    {"name": "ppt", "desc": "Juega a piedra, papel o tijera con el bot y gana o pierde coins.", "alias": ["/ppt"], "category": "economia", "uso": "piedra|papel|tijera"},
    {"name": "math", "desc": "Juega a resolver ecuación y gana o pierde coins.", "alias": ["/math", "/matematicas"], "category": "economia", "uso": "facil|medio|dificil|imposible|imposible2"},
    {"name": "waittimes", "desc": "Muestra tus tiempos de enfriamiento en las acciones de RPG.", "alias": ["/waittimes", "/cooldowns", "/economyinfo", "/einfo"], "category": "economia"},
    {"name": "economyboard", "desc": "Consulta el ranking de coins en el grupo.", "alias": ["/economyboard", "/baltop", "/eboard"], "category": "economia", "uso": "página"},
    {"name": "slut", "desc": "Prostitúyete y gana coins.", "alias": ["/slut"], "category": "economia"},
    {"name": "mine", "desc": "Realiza trabajos de minería y gana coins.", "alias": ["/mine"], "category": "economia"},
    {"name": "rt", "desc": "Apuesta coins en la ruleta de colores y prueba tu suerte.", "alias": ["/rt", "/roulette", "/ruleta"], "category": "economia", "uso": "cantidad + red|black|green"},
    {"name": "coinflip", "desc": "Apuesta coins a cara o cruz.", "alias": ["/coinflip", "/flip", "/cf"], "category": "economia", "uso": "bet"},
    {"name": "daily", "desc": "Reclama tu recompensa diaria.", "alias": ["/daily"], "category": "economia"},
    {"name": "monthly", "desc": "Reclama tus recompensas mensuales y disfruta tus beneficios.", "alias": ["/monthly", "/mensual"], "category": "economia"},
    {"name": "weekly", "desc": "Reclama tus recompensas semanales y disfruta tus beneficios.", "alias": ["/weekly", "/semanal"], "category": "economia"},
    {"name": "work", "desc": "Realiza un trabajo y gana coins.", "alias": ["/work", "/w"], "category": "economia"},
    {"name": "deposit", "desc": "Deposita coins en tu banco.", "alias": ["/deposit", "/dep", "/d"], "category": "economia", "uso": "cantidad|all"},
    {"name": "withdraw", "desc": "Retira coins de tu banco.", "alias": ["/withdraw", "/with"], "category": "economia", "uso": "cantidad|all"},

    // Gacha
    {"name": "rw", "desc": "Envia waifus aleatorios con valor.", "alias": ["/rw", "/roll", "/rollwaifu", "/rf"], "category": "gacha"},
    {"name": "c", "desc": "Compra una waifu.", "alias": ["/c", "/claim", "/buy"], "category": "gacha", "uso": "waifu"},
    {"name": "harem", "desc": "Mira tus personajes obtenidos.", "alias": ["/harem", "/miswaifus", "/claims"], "category": "gacha"},
    {"name": "sell", "desc": "Vende una waifu y gana coins.", "alias": ["/sell", "/vender"], "category": "gacha", "uso": "waifu + value"},
    {"name": "buyc", "desc": "Compra una waifu de la tienda.", "alias": ["/buyc", "/buycharacter", "/buychar"], "category": "gacha", "uso": "waifu"},
    {"name": "trade", "desc": "Intercambia una waifu por otra waifu.", "alias": ["/trade", "/cambiar"], "category": "gacha", "uso": "tu personaje / personaje 2"},
    {"name": "animelist", "desc": "Lista series del socket.", "alias": ["/animelist", "/slist", "/serielist"], "category": "gacha"},
    {"name": "animeinfo", "desc": "Información de un anime.", "alias": ["/animeinfo", "/ainfo", "/serieinfo"], "category": "gacha", "uso": "anime"},
    {"name": "tiendawaifus", "desc": "Verifica las waifus en ventas.", "alias": ["/tiendawaifus", "/listacompras", "/wshop", "/haremshop"], "category": "gacha"},
    {"name": "delrw", "desc": "Elimina una waifu de tu obtenidos.", "alias": ["/delrw", "/delp"], "category": "gacha", "uso": "waifu"},
    {"name": "removerventa", "desc": "Elimina una waifu de la venta.", "alias": ["/retirarventa"], "category": "gacha", "uso": "waifu"},
    {"name": "darrw", "desc": "Regala una waifu a un usuario.", "alias": ["/darrw", "/darp"], "category": "gacha", "uso": "mention + waifu"},
    {"name": "giveallharem", "desc": "Regala todas tus waifus a un usuario.", "alias": ["/giveallharem"], "category": "gacha", "uso": "mention"},
    {"name": "ginfo", "desc": "Ver los enfriamientos de los juegos gacha.", "alias": ["/ginfo", "/infogacha", "/gachainfo"], "category": "gacha"},
    {"name": "verpersonaje", "desc": "Ver la información de una waifu.", "alias": ["/vp"], "category": "gacha", "uso": "waifu"},
    {"name": "character", "desc": "Ver la info de tu waifu.", "alias": ["/character"], "category": "gacha", "uso": "waifu"},
    {"name": "vote", "desc": "Votar por una waifu y subir su valor.", "alias": ["/vote", "/votar"], "category": "gacha", "uso": "waifu"},
    {"name": "accepttrade", "desc": "Aceptar un intercambio de harems.", "alias": ["aceptar"], "category": "gacha", "uso": "solicitud"},
    {"name": "waifusboard", "desc": "Ver los usuarios con más waifus.", "alias": ["/toprw"], "category": "gacha", "uso": "mention"},
    {"name": "votesboard", "desc": "Ver los personajes con mas votos.", "alias": ["/topvotos", "/topwaifus"], "category": "gacha"},



    // Grupo
    {"name": "bot", "desc": "Activa y desactiva el bot en el grupo.", "alias": ["/bot"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "promote", "desc": "Promueve a un usuario a administrador.", "alias": ["/promote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "demote", "desc": "Degrada a un usuario de administrador.", "alias": ["/demote"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "setprimary", "desc": "Establece un bot como primario del grupo.", "alias": ["/setprimary"], "category": "grupo", "uso": "_<mention>_"},
    {"name": "warn", "desc": "Añade una advertencia a un usuario del grupo.", "alias": ["/warn"], "category": "grupo", "uso": "_<mention>_ + _<razón>_" },
    {"name": "topcount", "desc": "Top de usuarios con mas mensajes.", "alias": ["/topcount", "/topmessages", "/topmensajes", "/topmsgcount"], "category": "grupo"},
    {"name": "warns", "desc": "Muestra todas las advertencias registradas de un usuario.", "alias": ["/warns"], "category": "grupo", "uso": "_<mention>_" },
    {"name": "delwarn", "desc": "Elimina una advertencia específica de un usuario.", "alias": ["/delwarn"], "category": "grupo", "uso": "_<mention> <número|all>_" },
    {"name": "setwarnlimit", "desc": "Establece el límite máximo de advertencias permitidas en el grupo.", "alias": ["/setwarnlimit"], "category": "grupo", "uso": "_<número>_" },
    {"name": "clear", "desc": "Elimina usuarios inactivos tras 30 días, o consulta actividad con 'views'", "alias": ["/clear"], "category": "grupo", "uso": "_<delete|views>_"},
    {"name": "setgpbaner", "desc": "Cambia la imagen del grupo.", "alias": ["/setgpbaner"], "category": "grupo"},
    {"name": "setgpname", "desc": "Cambia el nombre del grupo.", "alias": ["/setgpname"], "category": "grupo", "uso": "_<text>_"},
    {"name": "setgpdesc", "desc": "Cambia la descripción del grupo.", "alias": ["/setgpdesc"], "category": "grupo", "uso": "_<text>_"},
    {"name": "closet", "desc": "Cierra y abre el grupo.", "alias": ["/closet", "/open"], "category": "grupo"},
    {"name": "options", "desc": "Desactiva o activa las configuraciones del grupo.", "alias": ["/welcome", "/bienvenidas", "/alerts", "/alertas", "/gacha", "/rpg", "/pokes", "/economy", "/economia", "/adminonly", "/onlyadmin", "/antilinks", "/antilink", "/antienlaces", "/owneronly", "/onlyowner"], "category": "grupo", "uso": "_<on|off>_"},
    {"name": "groupinfo", "desc": "Muestra la información del grupo.", "alias": ["/groupinfo", "/gp"], "category": "grupo"},
    {"name": "tag", "desc": "Menciona a todos los usuarios del grupo.", "alias": ["/tag", "/hidetag"], "category": "grupo", "uso": "_<text>_"},
    {"name": "kick", "desc": "Expulsa a un usuario del grupo.", "alias": ["/kick"], "category": "grupo", "uso": "_<mention>_"},


    // IA
    {"name": "ia", "desc": "Realiza una petición a chatgpt.", "alias": ["goku", "chatgpt", "ia"], "category": "ia", "uso": "query"},
    {"name": "dalle", "desc": "crea imagenes.", "alias": ["/dalle", "/aiimage"], "category": "ia", "uso": "descripción"},
    {"name": "aigensfw", "desc": "crea una imagen +18.", "alias": ["/aigensfw", "nsfwaigen", "pornogen"], "category": "ia", "uso": "descripción"},

    // Info
    {"name": "menu", "desc": "Muestra la lista de comandos.", "alias": ["/menu", "/help"], "category": "info", "uso": "category"},
    {"name": "infobot", "desc": "Muestra la información del socket.", "alias": ["/infobot", "/infosocket"], "category": "info"},
    {"name": "ping", "desc": "Muestra la velocidad del Bot.", "alias": ["/ping", "/p"], "category": "info"},
    {"name": "report", "desc": "Envia un mensaje de reporte al Staff.", "alias": ["/report", "/reporte"], "category": "info", "uso": "error"},
    {"name": "status", "desc": "Ver el estado del Bot.", "alias": ["/status"], "category": "info"},
    {"name": "sug", "desc": "Envia un mensaje de sugerencia al Staff.", "alias": ["/sug", "/suggest"], "category": "info", "uso": "suggest"},
    {"name": "invite", "desc": "Envia una sugerencia de un grupo a los moderadores.", "alias": ["/invitar", "/invite"], "category": "info", "uso": "link"},

    // NSFW
    {"name": "danbooru", "desc": "Buscar imágenes en danbooru.", "alias": ["/danbooru", "/dbooru"], "category": "nsfw", "uso": "text"},
    {"name": "gelbooru", "desc": "Buscar imágenes en gelbooru.", "alias": ["/gelbooru", "/gbooru"], "category": "nsfw", "uso": "text"},
    {"name": "rule34", "desc": "Buscar imágenes en rule34.", "alias": ["/rule34", "/r34"], "category": "nsfw", "uso": "text"},
    {"name": "hentai", "desc": "Imagenes random hentai.", "alias": ["/hentai"], "category": "nsfw", "uso": "ejecutar"},
    {"name": "xVideos", "desc": "Busca y descarga videos xxx", "alias": ["/buscarvideox", "/xvideosearch"], "category": "nsfw", "uso": "text"},
    {"name": "anal", "desc": "Partele el culo a alguien.", "alias": ["/anal"], "category": "nsfw", "uso": "tag"},
    {"name": "cum", "desc": "Llena de cum a alguien.", "alias": ["/cum"], "category": "nsfw", "uso": "tag"},
    {"name": "desnudar", "desc": "Desnuda a alguien.", "alias": ["/encuerar", "/undress"], "category": "nsfw", "uso": "tag"},
    {"name": "coger", "desc": "Follate a alguien.", "alias": ["/fuck", "/coger"], "category": "nsfw", "uso": "tag"},
    {"name": "nalgada", "desc": "Dale una nalgada a alguien.", "alias": ["/spank", "/nalgada"], "category": "nsfw", "uso": "tag"},
    {"name": "lickpussy", "desc": "Lamele el coño a ella.", "alias": ["/lickpussy"], "category": "nsfw", "uso": "tag"},
    {"name": "paja", "desc": "Haste una paja 🗣", "alias": ["/paja", "/fap",], "category": "nsfw", "uso": "tag"},
    {"name": "manosear", "desc": "Manosea a alguien.", "alias": ["/grope"], "category": "nsfw", "uso": "tag"},
    {"name": "69", "desc": "Hasle un 69 a alguien.", "alias": ["/69", "/sixnine"], "category": "nsfw", "uso": "tag"},
    {"name": "chupar tetas", "desc": "Chupale las tetas a alguien.", "alias": ["/suckboobs"], "category": "nsfw", "uso": "tag"},
    {"name": "agarrar tetas", "desc": "Agarrale las tetas a alguien.", "alias": ["/grabboobs"], "category": "nsfw", "uso": "tag"},
    {"name": "mamada", "desc": "Dale una mamada a alguien.", "alias": ["/bj", "/blowjob"], "category": "nsfw", "uso": "tag"},
    {"name": "rusa", "desc": "Hasle una rusa a alguien.", "alias": ["/boobjob"], "category": "nsfw", "uso": "tag"},
    {"name": "footjob", "desc": "Hasle una paja con los pies a alguien.", "alias": ["/footjob"], "category": "nsfw", "uso": "tag"},

    // Perfil
    {"name": "level", "desc": "Muestra información de tu nivel y progreso.", "alias": ["/level", "/levelup", "/lvl"], "category": "profile", "uso": "mention"},
    {"name": "marry", "desc": "Envia una solicitud de matrimonio a un usuario.", "alias": ["/marry"], "category": "profile", "uso": "mention"},
    {"name": "divorce", "desc": "Divorciate de tu pareja.", "alias": ["/divorce"], "category": "profile"},
    {"name": "profile", "desc": "Muestra tu perfil o la de un usuario.", "alias": ["/profile", "/perfil"], "category": "profile"},
    {"name": "setbirth", "desc": "Define una fecha de nacimiento a tu perfil.", "alias": ["/setbirth"], "category": "profile", "uso": "dia/mes/año|mes/dia"},
    {"name": "delbirth", "desc": "Elimina tu fecha de nacimiento actual del perfil.", "alias": ["/delbirth"], "category": "profile"},
    {"name": "setdescription", "desc": "Define una descripción a tu perfil.", "alias": ["/setdescription", "/setdesc"], "category": "profile", "uso": "text"},
    {"name": "deldescription", "desc": "Elimina tu descripción actual del perfil.", "alias": ["/deldescription", "/deldesc"], "category": "profile"},
    {"name": "setgenre", "desc": "Define un género a tu perfil.", "alias": ["/setgenre"], "category": "profile", "uso": "hombre|mujer"},
    {"name": "delgenre", "desc": "Elimina tu género actual del perfil.", "alias": ["/delgenre"], "category": "profile"},

    // Sockets
    {"name": "bots", "desc": "Muestra el número de sockets conectados.", "alias": ["/bots", "/sockets"], "category": "sockets"},
    {"name": "logout", "desc": "Cierra la sesión del socket.", "alias": ["/logout"], "category": "sockets"},
    {"name": "qr", "desc": "Vincular un nuevo socket a tu número.", "alias": ["/qr", "/code"], "category": "sockets"},
    {"name": "self", "desc": "Haz privado o público tu socket.", "alias": ["/self"], "category": "sockets", "uso": "on|off"},
    {"name": "set", "desc": "Modifica varias características del socket.", "alias": ["/set", "/edit"], "category": "sockets", "uso": "category + value"},
    {"name": "leave", "desc": "El bot abandona el grupo actual.", "alias": ["/leave"], "category": "sockets"},

    // Utilidades
    {"name": "sticker", "desc": "Convierte imágenes o videos a stickers.", "alias": ["/sticker", "/s"], "category": "utils"},
    {"name": "getpic", "desc": "Ver la foto de perfil de un usuario.", "alias": ["/getpic", "/pfp"], "category": "utils", "uso": "mention"},
    {"name": "tourl", "desc": "Convierte la imagen en un link.", "alias": ["/tourl"], "category": "utils"},
    {"name": "translate", "desc": "Traduce el texto al idioma especificado.", "alias": ["/translate"], "category": "utils", "uso": "idioma + text"},
    {"name": "get", "desc": "Realiza solicitudes get a páginas web.", "alias": ["/get"], "category": "utils", "uso": "url"},
    {"name": "setmeta", "desc": "Define los metadatos para tus stickers.", "alias": ["/setmeta"], "category": "utils", "uso": "packname | author"},
    {"name": "hd", "desc": "Mejora la calidad de una imagen.", "alias": ["/hd", "/upscale"], "category": "utils"},
    {"name": "rvocal", "desc": "Separa la vocal de una canción.", "alias": ["/rvocal"], "category": "utils"},
    {"name": "wm", "desc": "Cambia la marca de agua de un sticker.", "alias": ["/wm"], "category": "utils", "uso": "packname | author"},
    {"name": "tts", "desc": "Convierte texto a voz.", "alias": ["/tts", "/ttsvoz"], "category": "utils", "uso": "text"}
]
